#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:ctrl_modifier
    kb_rules =

    follow_mouse = 0
    mouse_refocus = true

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Wacom Cintiq 16 設定
device {
    name = wacom-cintiq-16-pen
    output = HDMI-A-1
}
